name: ciclozen
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.0.8
  intl: ^0.18.0
  shared_preferences: ^2.1.1
  sqflite: ^2.3.0
  path: ^1.8.3
  windows_notification: ^1.3.0
  sqflite_common_ffi:
  smooth_page_indicator: ^1.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/Absorvente.png
    - assets/Protetor.png
    - assets/Coletor.png
    - assets/Calcinha.png
    - assets/logo-removebg-preview.png
    - assets/logo.jpeg
    - assets/mestruacao.png
    
flutter_icons:
  android: true
  ios: true
  macos:
    generate: true
  windows:
    generate: true
  web:
    generate: true
  image_path: "assets/logo.jpeg"